config/routes.rb
Rails.application.routes.draw do
  get '/bookings/unconfirmed'
  get '/rooms/myrooms'
  get '/rooms/unauthorize'
  devise_for :users
  resources :cities
  resources :rooms do
    resources :special_prices
  end
  resources :amenities
  resources :bookings
  resources :dashboard
  

   root "cities#index"

end

app/models/special_price.rb
class SpecialPrice < ActiveRecord::Base
	belongs_to :rooms

end

app/controllers/special_prices_controller.rb
class SpecialPricesController < ApplicationController
	before_action :authenticate_user!
	load_and_authorize_resource	
	def index
		@special_prices = SpecialPrice.all
	end
	def new
		@special_price = SpecialPrice.new
	end

	def create
		@special_price = SpecialPrice.new(special_price_params)
         @special_price.room_id = params[:room_id]
		if @special_price.save
			redirect_to rooms_path, notice: "successfully cerated special price"
		else
			render :new
		end
	end

	private
	def special_price_params
		params[:special_price].permit(:room_id, :start_date, :end_date, :price)
	end
end

app/helpers/special_prices_helper.rb
module SpecialPricesHelper
end

app/views/special_prices/index.html.erb
<h2>Special prices </h2>

app/views/special_prices/new.html.erb
<h2>Special Price</h2>
<%= form_for @special_price, url: room_special_prices_path, method: :post do |f| %>
	<%=f.label :start_date %><br>
	<%=f.date_select :start_date %><br>

	<%=f.label :end_date %><br>
	<%=f.date_select :end_date %><br>

	

	<%= f.label :price %><br>
	<%=f.number_field :price %><br>

	<%= f.submit"submit" %>
	<% end %>