config/routes.rb
Rails.application.routes.draw do
  get '/bookings/unconfirmed'
  get '/rooms/myrooms'
  get '/rooms/unauthorize'
  devise_for :users
  resources :cities
  resources :rooms do
    resources :special_prices
  end
  resources :amenities
  resources :bookings
  resources :dashboard
  

   root "cities#index"

end

app/models/amenity.rb
class Amenity < ActiveRecord::Base
	has_many :amenity_rooms
	has_many :rooms, through: :amenity_rooms
	validates_presence_of :name, :description
end

app/controllers/amenities_controller.rb
class AmenitiesController < ApplicationController
	before_action :set_amenity, only: [:show, :edit, :update, :destroy]
	def index
		@amenities = Amenity.all
	end
	def new
		@amenity = Amenity.new
    end
    def create
    	@amenity = Amenity.new(amenity_params)
    	if @amenity.save
    		redirect_to amenities_path, notice: "successfully added amenity"
    	else
    		render :new
    	end
    end

    def show
    end
    def  edit
    end

    def update
			if @amenity.update_attributes(room_params)
				redirect_to amenity_path(@amenity.id), notice: "successfully Updated the amenity"
			else
				render action: "edit"
			end
		end
		def destroy
			@amenity = Amenity.find(params[:id])
			@amenity.destroy
			redirect_to amenities_path, notice: "successfully destroyed the amenity"
		end

 def set_amenity
	@amenity = Amenity.find(params[:id])
 end

 def amenity_params
	params[:amenity].permit(:name, :description)
 end
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/views/amenities/edit.html.erb
<h2>Edit the aminity </h2>
<%= form_for @amenity do |f| %>
	<label>name</label>
	<%= f.text_field :name %>
	<label>description</label>
	<%= f.text_field :description %>
    <%= f.submit %>
    <% end %>

app/views/amenities/index.html.erb
<h2>Listing aminities </h2>
<% @amenities.each do |amenity| %>
	Name - <%= amenity.name %><br>
	Description - <%= amenity.description %><br>
	<% end %>
	<%= link_to "new amenity",new_amenity_path %>


app/views/amenities/new.html.erb
<h2>Add aminities </h2>
<%= form_for  @amenity do |f| %>
	<div class ="field">
	<%= f.label :name  %>
	<%= f.text_field :name %><br>
	<div class ="text" >
	<%= f.label :description %>
	<%= f.text_area :description %><br>
	<div class ="actions">
	<%= f.submit %>
	<% end %>

app/views/amenities/show.html.erb
<p>
<strong>name</strong>
<%= @amenity.name  %>
</p>

<p>
<strong>descripiton</strong>
<%= @amenity.description %>
</p>

<%= link_to "Edit", edit_amenity_path(@amenity.id) %>
<%= link_to "destroy", amenity_path(@amenity.id), method: :delete, data: {confirm: "Are you sure"} %>
<%= link_to "listing Amenities", amenities_path %>