config/routes.rb
Rails.application.routes.draw do
  get '/bookings/unconfirmed'
  get '/rooms/myrooms'
  get '/rooms/unauthorize'
  devise_for :users
  resources :cities
  resources :rooms do
    resources :special_prices
  end
  resources :amenities
  resources :bookings
  resources :dashboard
  

   root "cities#index"

end

app/models/room.rb
class Room < ActiveRecord::Base
	mount_uploader :images, CoverUploader
	has_many :special_prices
	has_many :bookings
	belongs_to :city
	belongs_to :user
	has_many :reviews
	has_many :amenity_rooms
	has_many :amenities, through: :amenity_rooms
	validates_presence_of :name, :description, :price, :address, :rules, :city_id
	validates_length_of :description, within: (1..150)
 
 after_create :change_role
 before_save :search_lat_and_long
  def search_lat_and_long
	 response = HTTParty.get("http://maps.googleapis.com/maps/api/geocode/json?address=#{self.address}")
   		@result = JSON.parse(response.body)
     		self.latitude = @result["results"][0]["geometry"]["location"]["lat"]   
     		self.longitude = @result["results"][0]["geometry"]["location"]["lng"]
     	end
    	def change_role

    	 if self.user.role.name == "guest"
    		self.user.update_attributes(role_id:Role.second.id)
    	end
    end
end



   
	

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
	load_and_authorize_resource 
	before_action :set_room, only: [:show, :edit, :update, :destroy]
	def index
		@rooms = Room.where("is_authorized=?", true)
	end
	def new
		@room = Room.new
	end
	def create
		@room = Room.new(room_params)
		@room.user_id = current_user.id
		if @room.save

			redirect_to rooms_path
		else
			render :new
		end
	end
	def show
		@booking = Booking.new
		@review = Review.new
	end
	def edit
	end
	def update
			 if @room.update_attributes(room_params)
			 	 Notification.room_conformation(@room).deliver!
			  redirect_to room_path(@room.id), notice: "successfully Updated the room"
			else
				render action: "edit"
				
			end
		end
		def destroy
			@room.destroy
			redirect_to rooms_path, notice: "successfully destroyed the room"
		end
		def unauthorize
			@room = Room.where('is_authorized = ?', false)
		end
		def myrooms
			@rooms = current_user.rooms
		end


	private
	def set_room
		@room = Room.find(params[:id])
	end

	def room_params
		params[:room].permit(:name, :description, :price, :rules, :address, :images, :longitude, :latitude, :is_authorized, :city_id, :user_id, amenity_ids:[])
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<h2>editing room </h2>
<%= form_for @room do |f| %>

<label>name</label><br>
<%= f.text_field :name %><br>
<label>description</label><br>
<%= f.text_area :description %><br>
<label>price</label><br>
<%= f.text_field :price %><br>
<label>rules</label><br>
<%= f.text_field :rules %><br>
<label>images</label><br>
<%= f.file_field :images%><br>

<label>address</label><br>
<%= f.text_area :address %><br>

<%= f.submit %>
<% end %>

app/views/rooms/index.html.erb
<h2> Listing rooms </h2>
<table border=1>
<thead>
<tr>
<th>name </th>
<th>descrption</th>
<th>price</th>
<th>rules</th>
<th>images</th>
<th>Address</th>
<th>latitude</th>
<th>longitude</th>
</tr>
</thead>
<tbody>
<tr>
<% @rooms.each do |room| %>

<td><%= link_to room.name,room_path(room.id) %></td>
<td><%= room.description %></td>
<td><%= room.price %></td>
<td><%= room.rules %></td>
<td><%= room.images %></td>
<td><%= room.address %></td>
<td><%= room.latitude %></td>
<td><%= room.longitude %></td>
</tr>
<% end %>
</tbody>
</table>
<%= link_to "add room",new_room_path %>

app/views/rooms/myrooms.html.erb
<h2>Listing Rooms </h2>
<% if @rooms.empty? %>
	<h4>NO rooms</h4>
<% else %>
<% @rooms.each do |room| %>
	<li>
	<p>Name:<%= room.name %></p>
	<p>Description:<%= room.description %></p>
	<P>Address:<%= room.address %></P>
	<% end %>
	</li>
<% end %>

app/views/rooms/new.html.erb
<h2>Adding the room </h2>
<%= form_for @room do |f| %>
<% if @room.errors.any? %>
<h3> these errors prohibited the form to be  saved </h3>
<ul>
<% @room.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>


</ul>

<% end %>



<label>name</label></br>
<%= f.text_field :name %> <br>
<label>description</label><br>
<%= f.text_area :description %><br>
<label>price</label><br>
<%= f.text_field :price %><br>
<label>rules</label><br>
<%= f.text_field :rules %><br>
<label>address</label><br>
<%= f.text_area :address %><br>
<label>images</label><br>
<%= f.file_field :images%><br>

<label>city name </label>
<%= f.collection_select :city_id, City.all, :id, :name, prompt: "select city "
 %>
 <label>Amenity </label>
 <%= f.collection_check_boxes :amenity_ids, Amenity.all, :id, :name %>
<%= f.submit %>
<% end %>

app/views/rooms/show.html.erb
<%if @room.user_id == current_user.id %>
<%= link_to"special Price",new_room_special_price_path(@room.id) %>
<% end %>
<p>
<strong>name:</strong>
<%= @room.name  %>
</p>

<p>
<strong>descripiton</strong>
<%= @room.description %>
</p>

<p>
<strong>price</strong>
<%= @room.price %>
</p>

<p>
<strong>rules</strong>
<%= @room.rules %>
</p>

<p>
<strong>address</strong>
<%= @room.address %>
</p>
<p>
<strong>images:</strong>
<%= image_tag(@room.images.url) %>
</p>

<p>
<strong>latitude</strong>
<%= @room.latitude %>
</p>
<p>
<strong>longitude</strong>
<%= @room.longitude %>
</p>
<%= form_for @booking do |n| %>
<%= n.label "start_date" %><br>
<%= n.date_select :start_date %><br>
<%= n.label "end_date" %><br>
<%= n.date_select :end_date %><br>
<%= n.hidden_field :room_id, value:@room.id %>
<%= n.submit "book" %>
<% end %>

<%= link_to "Edit", edit_room_path(@room.id) %>
<%= link_to "destroy", room_path(@room.id), method: :delete, data: {confirm: "Are you sure"} %>
<%= link_to "listing rooms", rooms_path %>



app/views/rooms/unauthorize.html.erb


<% @room.each do |n| %>
<ol>
<%= n.name  %>

</ol>

<%= form_for n do |t| %>
	<%= t.hidden_field :is_authorized, value:true %>
	<%= t.submit "authorize" %>
	<% end %>
<% end %>