config/routes.rb
Rails.application.routes.draw do
  get '/bookings/unconfirmed'
  get '/rooms/myrooms'
  get '/rooms/unauthorize'
  devise_for :users
  resources :cities
  resources :rooms do
    resources :special_prices
  end
  resources :amenities
  resources :bookings
  resources :dashboard
  

   root "cities#index"

end

app/models/city.rb
class City < ActiveRecord::Base
     has_many :rooms
	validates_presence_of :name
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	load_and_authorize_resource
	def index
		@cities = City.all
	end
	def new
		@city = City.new
	end

	def create
		@city = City.new(city_params)
		if @city.save
			redirect_to cities_path, notice: "successfully added City"
		else
			render :new
		end
	end
		def show
			@city = City.find(params[:id])
		end
		def edit
			@city = City.find(params[:id])
		end
		def update
			if @city.update_attributes(city_params)
				redirect_to city_path(@city.id), notice: "successfully Updated the city"
			else
				render action: "edit"
			end
		end
		def destroy
			@city = City.find(params[:id])
			@city.destroy
			redirect_to cities_path, notice: "successfully destroyed the room"
		end


	 private
	  def city_params
		params[:city].permit(:name)
	   end

end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/edit.html.erb
<h2> edit City </h2>
<%= form_for @city do |f| %>

<div class ="field">
<%= f.label :cityname %>
<%= f.text_field :name %>
<div class ="actions" %>
<%= f.submit %>
<% end %>

app/views/cities/index.html.erb
<h2> Listing the cities </h2>
<% @cities.each do |city| %>
	<%= city.name  %></br>
     <% end %>

     <%= link_to "new city",new_city_path %> 

app/views/cities/new.html.erb
<h2> Add Cities </h2>
<%= form_for @city do |f| %>

<div class ="field">
<%= f.label :cityname %>
<%= f.text_field :name %>
<div class ="actions" %>
<%= f.submit %>
<% end %>

app/views/cities/show.html.erb
<%=@city.name %>

<%= link_to "Edit", edit_city_path(@city.id) %>
<%= link_to "destroy", city_path(@city.id), method: :delete, data: {confirm: "Are you sure"} %>
<%= link_to "listing cities", cities_path %>